builder_name:
  xpath: "//input[@id='npxidBUILDER_NAME']/@value"
project_name:
  xpath: "//input[@id='npxidPROJ_NAME']/@value"
address:
  xpath: "//input[@id='npxidPROJ_ADD']/@value"
locality:
  xpath: "//input[@id='npxidPROJ_LOCALITY']/@value"
city:
  xpath: "//input[@id='npxidPROJ_CITY']/@value"
min_price:
  xpath: "//input[@id='npxidMIN_PRICE']/@value"
max_price:
  xpath: "//input[@id='npxidMAX_PRICE']/@value"
min_area:
  xpath: "//input[@id='npxidMIN_AREA_SQFT']/@value"
max_area:
  xpath: "//input[@id='npxidMAX_AREA_SQFT']/@value"
latitude:
  xpath: "//input[@id='npxidLATITUDE']/@value"
longitude:
  xpath: "//input[@id='npxidLONGITUDE']/@value"

status:
  xpath: "//div[@id='overviewSection']//div[@class='factBox'][1]//div[@class='factVal1']/text()"
completion_year: 
  xpath: "//div[@id='overviewSection']//div[@class='factBox'][1]//div[@class='factVal2']/text()"
  process: ["re.sub('Completed in', '', project['completion_year']).strip()", "re.findall('[0-9]+', project['completion_year'])[0]"]
completion_month:
  xpath: "//div[@id='overviewSection']//div[@class='factBox'][1]//div[@class='factVal2']/text()"
  process: ["re.sub('Completed in', '', project['completion_month']).strip()", "re.findall('[a-zA-Z]+', project['completion_month'])[0]"]
units_towers:
  xpath: "//i[@class='xid_icons xid_icons_1x xid_project_details']/ancestor::div[@class='factData']/div[@class='factVal1']/text()"
building_type:
  xpath: "//div[@id='overviewSection']//div[@class='factBox'][4]//div[@class='factVal1']/text()"
unit_bhk_types:
  xpath: "//div[@id='overviewSection']//div[@class='factBox'][4]//div[@class='factVal2']/text()"
  process: ["re.findall('[0-9]+', project['unit_bhk_types'])"]
total_area:
  xpath: "//div[@id='overviewSection']//div[@class='factBox'][6]//div[@class='factVal1']/text()"
  process: ["re.findall('\\d+\\.*\\d*', project['total_area'])[0]"]

# floor_plans
unit_bhk:
  xpath: "//div[@class='floorPlanContainer']//div[@id='unitDetContainer']/div[@class='fpcRow flt flex qaOptionTuple dev_optionTuple']/@data-property-type"
super_built_up_area:
  xpath: "//div[@class='floorPlanContainer']//div[@id='unitDetContainer']/div[@class='fpcRow flt flex qaOptionTuple dev_optionTuple']/div[contains(@class,'qaAreaDiv')]/div/span/text()[contains(.,'Super Built-up Area')]/parent::span/parent::div/span[@class='jumboText']/text()"
carpet_area:
  xpath: "//div[@class='floorPlanContainer']//div[@id='unitDetContainer']/div[@class='fpcRow flt flex qaOptionTuple dev_optionTuple']/div[contains(@class,'qaAreaDiv')]/div/span/text()[contains(.,'Carpet Area')]/parent::span/parent::div/span[@class='jumboText']/text()"
new_booking_base_price:
  xpath: "//div[@class='floorPlanContainer']//div[@id='unitDetContainer']/div[@class='fpcRow flt flex qaOptionTuple dev_optionTuple']/div[contains(@class,'qaNewBookingPriceDiv')]//span/text()"
rooms:
  xpath: "//div[@class='floorPlanContainer']//div[@id='unitDetContainer']/div[@class='fpcRow flt flex qaOptionTuple dev_optionTuple']/div[contains(@class,'qaInclusions')]/text()"




